/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nekoperudo.IHM;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
 
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
/**
 *
 * @author Pascal
 */
public class Fenetre extends javax.swing.JFrame {

    //Les deux panels de ta fenetre
    Panel1 panel1 = new Panel1();
    Panel2 panel2 = new Panel2();
    //Le bouton qui va changer le panel
    //JButton bChangerPanel = new JButton("Tester changement");
     
    //Constructeur de ta fenêtre
    public Fenetre(){
        //Paramètres (tu règles selon tes envies)
        super("Fenetre de test");
        this.setSize(1000, 600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        
        //Ecouteur sur le bouton
        //this.bChangerPanel.addActionListener(new EcouteurBoutonChanger());
        //panel1.jButton1.addActionListener(new EcouteurBoutonChanger());
        //Par défaut, on place le bouton dans le premier panel qui est dans la fenêtre
        //this.panel1.add(this.bChangerPanel);
        this.setContentPane(this.panel1);
        //Couleur des panels (pour voir le changement)
        //this.panel1.setBackground(Color.red);
        
    }
     
    //Méthode qui change le panel de ta fenêtre
    public void changerMenu(){
        this.setContentPane(this.panel2);
        this.revalidate();
    }
     
    //Ecouteur de ton bouton
    public class EcouteurBoutonChanger implements ActionListener{
        public void actionPerformed(ActionEvent clic) {
            //Appelle la méthode de changement de panel
            Fenetre.this.changerMenu();
        }
    }
     
    //Lanceur
    public static void main(String[] args){
        Fenetre fen = new Fenetre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
