package nekoperudo.IHM;

import static java.lang.Thread.sleep;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import nekoperudo.IfJoueur.JoueurNotificationImpl;
import nekoperudo.IfJoueur.Nekoperudo;

public class FileAttente extends javax.swing.JDialog {
    
    String pseudo;
    String serveur;
    Nekoperudo proxy;
    JoueurNotificationImpl notif;
    
    public FileAttente(String pseudo, String serveur, Nekoperudo pProxy, JoueurNotificationImpl pNotif) {
        
        initComponents();
        this.pseudo = pseudo;
        this.serveur = serveur;
        this.proxy = pProxy;
        this.notif = pNotif;

        /*Image*/
        ImageIcon icone = new ImageIcon("C:/Firefox_baby.png");
        JLabel image = new JLabel(icone);
        image.setSize(jPanel1.getWidth(), jPanel1.getHeight());
        jPanel1.add(image);
        jPanel1.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPret = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonPret.setText("Pret");
        jButtonPret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPretMouseClicked(evt);
            }
        });
        jButtonPret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Attente de joueurs ....");

        jLabel7.setText("La partie commencera quand tout les joueurs seront prêts");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(jButtonPret)))
                .addContainerGap(373, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addComponent(jButtonPret)
                .addGap(285, 285, 285))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretActionPerformed
        
        try {
            proxy.JoueurPret(pseudo, notif);
        } catch (RemoteException ex) {
            Logger.getLogger(FileAttente.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jButtonPretActionPerformed

    private void jButtonPretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPretMouseClicked
     //   jButtonPret.setEnabled(false);
    }//GEN-LAST:event_jButtonPretMouseClicked
    
    public String frameInitialiserPartie(String pAToiDeJouer) throws RemoteException, InterruptedException {
        int i;
        this.setVisible(false);
        //runFrameInitialiserPartie(pAToiDeJouer);

        try {
            sleep(250);
        } catch (InterruptedException ex) {
            Logger.getLogger(FileAttente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String[] stringDecoupepAToiDeJouer = pAToiDeJouer.split(",");
        boolean baToiDeJouer = Boolean.parseBoolean(stringDecoupepAToiDeJouer[1]);
        
        pAToiDeJouer = pAToiDeJouer.replace(",false", "");
        pAToiDeJouer = pAToiDeJouer.replace(",true", "");
        String[] stringDecoupeGobelet = pAToiDeJouer.split(" ");
        int[] intDecoupeGobelet = new int[stringDecoupeGobelet.length];
        
        for (i = 0; i < stringDecoupeGobelet.length; i++) {
            intDecoupeGobelet[i] = Integer.parseInt(stringDecoupeGobelet[i]);
        }
        
        ChoixAction c1 = new ChoixAction(pseudo, serveur, proxy, notif, baToiDeJouer, intDecoupeGobelet);
        c1.setTitle("Nekorudo : " + pseudo);
        c1.setLocationRelativeTo(null);
        c1.setVisible(true);
        notif.setChoixAction(c1);
        
        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonPret;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
