/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nekoperudo.IHM;

import javax.swing.JFrame;

/**
 *
 * @author Pascal
 */
public class Regles extends javax.swing.JFrame {

    String pseudo;

    
    
    
    /**
     * Creates new form Règles
     */
    public Regles(String pseudo) {
        initComponents();
        this.pseudo = pseudo;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Le PERUDO est un jeu de société dont le but consiste à être le dernier joueur à posséder un ou\nplusieurs dés.\nEn début de partie, chaque joueur (au nombre maximum de 6) prend un gobelet et les 5 dés\ncorrespondant à sa couleur. Le premier joueur à jouer est défini aléatoirement et la partie se poursuit dans\nl’ordre des aiguilles d’une montre.\nLa partie se déroule de la manière suivante :\n- les joueurs mélangent leurs dés, ils sont alors les seuls à connaître la valeur des dés mélangés ;\n- le premier joueur doit faire une proposition : il doit annoncer un nombre de dés ainsi qu’une\nvaleur de dés ;\n- le joueur suivant dispose de trois choix :\n- Faire une nouvelle proposition qui va surenchérir la précédente (soit en augmentant le\nnombre de dés, soit en augmentant la valeur ou bien les deux) ;\n- Déclarer que le joueur précédent ment. Ici, tous les joueurs vont dévoiler leurs dés. Si le\nnombre annoncé par le joueur précédent est inférieur à ceux sur la table alors il perd un\ndé. Sinon c’est le joueur qui l’a accusé qui perd un dé ;\n- Déclarer le “tout-pile”. Ici, tous les joueurs vont dévoilés leur dés. Si le nombre de dés\nannoncé vaut exactement ceux sur la table alors le joueur gagne un dé, sinon il en perd\nun.\n- Si une nouvelle proposition a été annoncée, le tour continue. Si un joueur a gagné ou perdu un dé,\nun nouveau tour commence avec ce dit-joueur qui va annoncer une nouvelle proposition (il n’est\npas obligé de surenchérir la dernière proposition ).\nLes dés peuvent prendre comme valeur : PERUDO, 2, 3, 4, 5 et 6. La valeur PERUDO est une\nvaleur de dé qui prend en valeur celle du dé annoncé (il s’agit donc d’une sorte de joker).");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Règles du jeu");

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(386, 386, 386))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String pseudo) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Regles reg = new Regles(pseudo);
                reg.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                reg.setTitle("Nekorudo");
                reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
                reg.setLocationRelativeTo(null);
                reg.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
